development:
  access_key_id: AKIAILFJ5K2P64AMVYZQ
  secret_access_key: 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

production:
  access_key_id: AKIAILFJ5K2P64AMVYZQ
  secret_access_key: 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

